package top.kinoz.mapper;

import java.util.List;
import top.kinoz.pojo.dept;

public interface deptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    int insert(dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    dept selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    List<dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    int updateByPrimaryKey(dept record);
}