package top.kinoz.mapper;

import java.util.List;
import top.kinoz.pojo.emp;

public interface empMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    int deleteByPrimaryKey(Integer eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    int insert(emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    emp selectByPrimaryKey(Integer eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    List<emp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    int updateByPrimaryKey(emp record);
}