package top.kinoz.pojo;

public class dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_name
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private String dName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_id
     *
     * @return the value of department.d_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_id
     *
     * @param dId the value for department.d_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_name
     *
     * @return the value of department.d_name
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_name
     *
     * @param dName the value for department.d_name
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }


    @Override
    public String toString() {
        return "dept{" +
                "dId=" + dId +
                ", dName='" + dName + '\'' +
                '}';
    }
}