package top.kinoz.pojo;

public class emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_name
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.age
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.d_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.collage
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    private String collage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_id
     *
     * @return the value of employee.e_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_id
     *
     * @param eId the value for employee.e_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_name
     *
     * @return the value of employee.e_name
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_name
     *
     * @param eName the value for employee.e_name
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.age
     *
     * @return the value of employee.age
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.age
     *
     * @param age the value for employee.age
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sex
     *
     * @return the value of employee.sex
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sex
     *
     * @param sex the value for employee.sex
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.d_id
     *
     * @return the value of employee.d_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.d_id
     *
     * @param dId the value for employee.d_id
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.collage
     *
     * @return the value of employee.collage
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public String getCollage() {
        return collage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.collage
     *
     * @param collage the value for employee.collage
     *
     * @mbggenerated Thu Dec 29 16:47:09 CST 2022
     */
    public void setCollage(String collage) {
        this.collage = collage == null ? null : collage.trim();
    }


    @Override
    public String toString() {
        return "emp{" +
                "eId=" + eId +
                ", eName='" + eName + '\'' +
                ", age=" + age +
                ", sex='" + sex + '\'' +
                ", email='" + email + '\'' +
                ", dId=" + dId +
                ", collage='" + collage + '\'' +
                '}';
    }
}